### ISSUE TITLE
[1.12.2] Mixin or FancyMenu loading stuff to early?

### ISSUE THREAD

**Issue by Runburner** [Keksuccino/FancyMenu#158]
**Describe the bug**
Hit play on the Minecraft Launcher and it minimizes. Comes right back up with an error code saying the game crashed. Minecraft doesn't even open the FML loading screen.

**To Reproduce**
I'm unsure how to reproduce what exactly is causing this issue. I've got a lot of mods, but the game isn't even starting. I hit play and a few seconds after it just crashes. If you need more information outside the crash log let me know and I will do what I can to get you the info.

**Crash Log**
`Mixin prepare failed preparing MixinGuiScreen in fancymenu.general.mixin.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: fancymenu.general.mixin.json:MixinGuiScreen target net.minecraft.client.gui.GuiScreen was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: fancymenu.general.mixin.json:MixinGuiScreen target net.minecraft.client.gui.GuiScreen was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:937)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:871)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:713)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:650)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
19:09:05.794
LaunchWrapper
main
Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fancymenu.general.mixin.json:MixinGuiScreen] from phase [DEFAULT] in config [fancymenu.general.mixin.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:591)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:518)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: fancymenu.general.mixin.json:MixinGuiScreen target net.minecraft.client.gui.GuiScreen was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:937)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:871)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:713)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:650)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515)
	... 14 more`

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version [2.0.6-1.12-1.12.2]
 - Forge/Fabric Version [14.23.5.2854]
 - Minecraft Version [1.12.2]
 - Active Mods [138 Mods, can post list if needed.]

**Comment by Keksuccino** [comment]
Hi! Most probably a mod conflict, not FM's fault.
Try to load the game with only FancyMenu, Konkrete and MixinBootstrap installed, please.

**Comment by Runburner** [comment]
It launches normally with just those installed plus Optifine. Would you like me to send my modlist or do you know of any conflicting mods already?

**Comment by Keksuccino** [comment]
There are some incompatible mods listed in this [incompatibility list](http://fm.keksuccino.de/books/fancymenu-v20x/page/20x-incompatibility-list).

I don’t really have time to check all your mods, that’s the problem :/

But you can send me a full log (located at `.minecraft/logs/latest.log`) with all mods installed (should show the error), if you want. Maybe I can find something Mixin related or core mod related there. The incompatibility is either caused by another mod using Mixin or a core mod.
