### ISSUE TITLE
Player Entity element spams with errors

### ISSUE THREAD

**Issue by MJRamon** [Keksuccino/FancyMenu#253]
**Describe the bug**
If Player Entity element is used, console gets spammed like crazy with this:

```
[21:04:16] [Render thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_19538()" because "$$0" is null
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1297.method_5858(class_1297.java:1410)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_976.handler$cgm001$render(class_976.java:1040)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_976.method_17159(class_976.java)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_976.method_4199(class_976.java:33)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_922.method_4054(class_922.java:145)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerRenderer.render(PlayerEntityCustomizationItem.java:455)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderEntityStatic(PlayerEntityCustomizationItem.java:321)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.lambda$renderPlayerEntity$0(PlayerEntityCustomizationItem.java:294)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1149)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderPlayerEntity(PlayerEntityCustomizationItem.java:293)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.render(PlayerEntityCustomizationItem.java:238)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.menuhandler.MenuHandlerBase.onRenderPost(MenuHandlerBase.java:1248)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.menuhandler.custom.MainMenuHandler.onRenderPost(MainMenuHandler.java:116)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.invokeEvent(EventHandler.java:115)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.callEventsFor(EventHandler.java:102)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.redirect$bmp000$onRenderCurrentScreen(class_757.java:4537)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:875)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1117)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:733)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:238)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:04:16] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version fancymenu_fabric_2.6.4_MC_1.18-1.18.1
 - Fabric 0.12.12
 - Minecraft 1.18.1
 - Active Mods: no Optifine

**Comment by Keksuccino** [comment]
That's a mod incompatibility. Please try to start the game with only FancyMenu + dependencies installed and see if this fixes the issue.

**Comment by Keksuccino** [comment]
Closed because no response and most probably just an incompatibility issue.

**Comment by MJRamon** [comment]
I've narrowed the problem - there's conflict with ["3dSkinLayers" mod](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d/) (3dskinlayers-fabric-1.4.3-mc1.18.2.jar is used, latest version).

Can it be resolved?
