### ISSUE TITLE
Player Entity element: Parrot not showing on arm when 3D Skin Layers mod is installed

### ISSUE THREAD

**Issue by TheeMrCheeky** [Keksuccino/FancyMenu#268]
**Describe the bug**
it only happens on the main screen noticed it in multiplayer screen as well

**To Reproduce**
make new element
player entity 
right click and enable show parrot

![image](https://user-images.githubusercontent.com/96976998/166571723-f6e1bad9-1375-447a-9091-30fd37ed1e4c.png)

 - OS: windows 11
 - FancyMenu Version fancymenu_fabric_2.7.0_MC_1.18.2.jar
 - Forge/Fabric Version 0.14.0
 - Minecraft Version 1.18.2
 - Active Mods Multiple mods

**Comment by Nick1st** [comment]
Please send the following information:

- [ ] modlist 
- [ ] latest.log

**Comment by TheMrCheeky** [comment]
[latest.log](https://github.com/Keksuccino/FancyMenu/files/8645535/latest.log)
[modlist.txt](https://github.com/Keksuccino/FancyMenu/files/8645536/modlist.txt)

**Comment by Nick1st** [comment]
Can you maybe try without `Skin Layers 3D`?

**Comment by TheMrCheeky** [comment]
ahh good call ya it works with out Skin Layers 3D, Crazy its only on like main menu multiplayer just the main screens there. But ya works. So is that on their end then?

**Comment by Nick1st** [comment]
It's a incompatibility @Keksuccino need to have a look at, and then decide if it's fixable on his side.

**Comment by TheMrCheeky** [comment]
Well glad we could figure it out! Hopefully he can. Thanks for helping

**Comment by Keksuccino** [comment]
I don't think I can fix this on my end, sorry :/

**Comment by Nick1st** [comment]
Once this https://github.com/tr7zw/3d-Skin-Layers/issues/60 gets closed, this issue might go away.

**Comment by TheMrCheeky** [comment]
Issue still is there. Sadly

**Comment by Fefedu973** [comment]
Still does not work with last version of skin layers 3d but this time it dont render at all

error : 
java.lang.ClassCastException: class de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerEntity cannot be cast to class net.minecraft.class_742 (de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerEntity and net.minecraft.class_742 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @2473b9ce)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_591.handler$coo000$setupAnimEnd(class_591.java:540)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_591.method_17087(class_591.java:179)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_591.method_2819(class_591.java:22)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_922.method_4054(class_922.java:129)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerRenderer.render(PlayerEntityCustomizationItem.java:453)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderEntityStatic(PlayerEntityCustomizationItem.java:317)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.lambda$renderPlayerEntity$0(PlayerEntityCustomizationItem.java:292)
[17:47:35] [Render thread/INFO]: [STDERR]:     at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderPlayerEntity(PlayerEntityCustomizationItem.java:291)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.render(PlayerEntityCustomizationItem.java:236)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.menuhandler.MenuHandlerBase.onRenderPost(MenuHandlerBase.java:1246)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.menuhandler.custom.MainMenuHandler.onRenderPost(MainMenuHandler.java:117)
[17:47:35] [Render thread/INFO]: [STDERR]:     at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
[17:47:35] [Render thread/INFO]: [STDERR]:     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:47:35] [Render thread/INFO]: [STDERR]:     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.konkrete.events.EventHandler.invokeEvent(EventHandler.java:115)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.konkrete.events.EventHandler.callEventsFor(EventHandler.java:102)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_757.handler$ccm000$beforeRenderScreen(class_757.java:6047)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_757.method_3192(class_757.java:877)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_310.method_1523(class_310.java:1122)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_310.method_1514(class_310.java:737)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.client.main.Main.main(Main.java:236)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Keksuccino** [comment]
Skin Layers 3D should work fine with FancyMenu for MC 1.16+ now!
Added support for it in FancyMenu v2.7.2-1!
