### ISSUE TITLE
The game keeps crashing!

### ISSUE THREAD

**Issue by ixDarkLorD** [Keksuccino/FancyMenu#382]
**Describe the bug**
The game keeps crashing when I launch the game. Because of the animation!
And I'm sure of installing it right.

**To Reproduce**
1. Creating the animation from the animation maker tool
2. Putting the files in the game directory
3. Launch the game
4. And, boom crashed!

**Expected behavior**
I expected the game to run properly!

**Game Log**
[latest.log](https://pastebin.com/YNGcT357)
[Crash Report](https://pastebin.com/zyDBZNqG)

**Screenshots**
https://imgur.com/RVArGTE

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version 2.12.2
 - Forge/Fabric Version 43.1.0
 - Minecraft Version 1.19.2
 - Active Mods [Load My Resources, MP Manager]

**Comment by Plagueistry** [comment]
Same here!

**Comment by Keksuccino** [comment]
Please try to start the game with only FancyMenu + dependencies installed.

**Comment by Plagueistry** [comment]
So I did that made a fresh animation file from the animation maker program, copy and pasted correctly, start the game and get exit code -1.

**Comment by Plagueistry** [comment]
also if this tells you anything or helps in anyway idk let me know what to do from here.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.server.packs.repository.Pack.m_10430_(Pack.java:40) ~[client-1.19.2-20220805.130853-srg.jar%23152!/:?] {re:classloading}
	at de.keksuccino.fancymenu.menu.animation.v2.resource.AnimationRepositorySource.m_7686_(AnimationRepositorySource.java:48) ~[fancymenu_forge_2.12.2_MC_1.19-1.19.2.jar%23146!/:1.0.0] {re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:47) ~[client-1.19.2-20220805.130853-srg.jar%23152!/:?] {re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23152!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23152!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by Plagueistry** [comment]
also one last thing @Keksuccino thank you for this mod, seriously, I've always wanted my "own" version of minecraft and this has helped me feel right at home with other modpack creators. I've already done a little workaround by having a flat image as the background and using a video element behind the vanilla buttons to sort of do what I was hoping for (just not as cleanly) so the idea is there and it makes me so happy to see my modpack logo pop up when I boot the game. So again thank you! And job well done replying so quickly too!

**Comment by Keksuccino** [comment]
> So I did that made a fresh animation file from the animation maker program, copy and pasted correctly, start the game and get exit code -1.

Please send me your full `logs/latest.log` file again after starting the game without other mods.

> also one last thing @Keksuccino thank you for this mod, seriously, I've always wanted my "own" version of minecraft and this has helped me feel right at home with other modpack creators. I've already done a little workaround by having a flat image as the background and using a video element behind the vanilla buttons to sort of do what I was hoping for (just not as cleanly) so the idea is there and it makes me so happy to see my modpack logo pop up when I boot the game. So again thank you! And job well done replying so quickly too!

Aw, thank you very much! :)

**Comment by Plagueistry** [comment]
Here it is sorry idk what to use to send you the actual file

[13:54:37] [main/INFO]: ModLauncher running: args [--username, Plagueistry, --version, forge-43.1.25, --gameDir, C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test, --assetsDir, C:\Users\Senpa\curseforge\minecraft\Install\assets, --assetIndex, 1.19, --uuid, e585683dcffb4ff5997b819ffccb34c7, --accessToken, ????????, --clientId, NDYyNWM0NzUtMTc4Yy00NDViLTljOGMtODMxZWYzODA4NDQ3, --xuid, 2533274875158405, --userType, msa, --versionType, release, --width, 1920, --height, 1080, --launchTarget, forgeclient, --fml.forgeVersion, 43.1.25, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[13:54:37] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[13:54:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Senpa/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[13:54:37] [main/INFO]: Found mod file auudio_forge_1.0.3_MC_1.19.jar of type MOD with provider {mods folder locator at C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test\mods}
[13:54:37] [main/INFO]: Found mod file fancymenu_forge_2.12.2_MC_1.19-1.19.2.jar of type MOD with provider {mods folder locator at C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test\mods}
[13:54:37] [main/INFO]: Found mod file fancymenu_video_extension_forge_1.1.1_MC_1.19-1.19.2.jar of type MOD with provider {mods folder locator at C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test\mods}
[13:54:37] [main/INFO]: Found mod file FancyVideo-API-forge-2.2.0.1.jar of type MOD with provider {mods folder locator at C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test\mods}
[13:54:37] [main/INFO]: Found mod file fm_audio_extension_forge_1.1.1-1_MC_1.19.jar of type MOD with provider {mods folder locator at C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test\mods}
[13:54:37] [main/INFO]: Found mod file konkrete_forge_1.5.0_MC_1.19-1.19.1.jar of type MOD with provider {mods folder locator at C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test\mods}
[13:54:37] [main/INFO]: Found mod file loadmyresources_1.0.1_MC_1.19 (1).jar of type MOD with provider {mods folder locator at C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test\mods}
[13:54:37] [main/WARN]: Mod file C:\Users\Senpa\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.19.2-43.1.25\fmlcore-1.19.2-43.1.25.jar is missing mods.toml file
[13:54:37] [main/WARN]: Mod file C:\Users\Senpa\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.1.25\javafmllanguage-1.19.2-43.1.25.jar is missing mods.toml file
[13:54:37] [main/WARN]: Mod file C:\Users\Senpa\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.1.25\lowcodelanguage-1.19.2-43.1.25.jar is missing mods.toml file
[13:54:37] [main/WARN]: Mod file C:\Users\Senpa\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.19.2-43.1.25\mclanguage-1.19.2-43.1.25.jar is missing mods.toml file
[13:54:37] [main/INFO]: Found mod file fmlcore-1.19.2-43.1.25.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@712ca57b
[13:54:37] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.1.25.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@712ca57b
[13:54:37] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.1.25.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@712ca57b
[13:54:37] [main/INFO]: Found mod file mclanguage-1.19.2-43.1.25.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@712ca57b
[13:54:37] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@712ca57b
[13:54:37] [main/INFO]: Found mod file forge-1.19.2-43.1.25-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@712ca57b
[13:54:37] [main/INFO]: No dependencies to load found. Skipping!
[13:54:39] [main/INFO]: Compatibility level set to JAVA_17
[13:54:39] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-43.1.25, --gameDir, C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test, --assetsDir, C:\Users\Senpa\curseforge\minecraft\Install\assets, --uuid, e585683dcffb4ff5997b819ffccb34c7, --username, Plagueistry, --assetIndex, 1.19, --accessToken, ????????, --clientId, NDYyNWM0NzUtMTc4Yy00NDViLTljOGMtODMxZWYzODA4NDQ3, --xuid, 2533274875158405, --userType, msa, --versionType, release, --width, 1920, --height, 1080]
[13:54:39] [main/INFO]: APPLYING MIXIN: de.keksuccino.auudio.mixin.client.MixinSoundBufferLibrary | TO TARGET: net.minecraft.client.sounds.SoundBufferLibrary
[13:54:39] [main/INFO]: APPLYING MIXIN: de.keksuccino.auudio.mixin.client.MixinSoundEngine | TO TARGET: net.minecraft.client.sounds.SoundEngine
[13:54:42] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[13:54:43] [Render thread/WARN]: Assets URL 'union:/C:/Users/Senpa/curseforge/minecraft/Install/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23152!/assets/.mcassetsroot' uses unexpected schema
[13:54:43] [Render thread/WARN]: Assets URL 'union:/C:/Users/Senpa/curseforge/minecraft/Install/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23152!/data/.mcassetsroot' uses unexpected schema
[13:54:43] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:54:43] [Render thread/INFO]: Setting user: Plagueistry
[13:54:44] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[13:54:44] [modloading-worker-0/WARN]: ## WARNING ## 'FancyVideo-API' is modifying this log! Disable this behavior in its config BEFORE reporting bugs!
[13:54:44] [modloading-worker-0/INFO]: Initialized!
[13:54:44] [modloading-worker-0/INFO]: [LOAD MY RESOURCES] PackHandler initialized!
[13:54:44] [modloading-worker-0/INFO]: Running on OS: windows amd64
[13:54:44] [modloading-worker-0/INFO]: Forge mod loading, version 43.1.25, for MC 1.19.2 with MCP 20220805.130853
[13:54:44] [modloading-worker-0/INFO]: MinecraftForge v43.1.25 Initialized
[13:54:44] [modloading-worker-0/INFO]: [KONKRETE] Successfully initialized!
[13:54:44] [modloading-worker-0/INFO]: [KONKRETE] Server-side libs ready to use!
[13:54:44] [modloading-worker-0/INFO]: [FANCYMENU] AnimationHandler: Animation registered: opalfiresplash
[13:54:44] [modloading-worker-0/INFO]: Native VLC Found at 'C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test'
[13:54:44] [modloading-worker-0/INFO]: [FANCYMENU] Loading mod in client-side mode!
[13:54:45] [Render thread/INFO]: [FancyMenu] Animation packs registered!
[13:54:45] [Render thread/INFO]: [LOAD MY RESOURCES] Pack registered!
[13:54:45] [Render thread/FATAL]: Preparing crash report with UUID c3975233-1cd9-4001-b9b6-d2bbb8dc045c
[13:54:45] [Render thread/FATAL]: Preparing crash report with UUID 6548f483-e83a-446a-b91c-213fa4d09d4e
[13:54:45] [Thread-2/INFO]: Running FancyVideo-API shutdown hook
[13:54:45] [Thread-2/INFO]: Running shutdown
[13:54:45] [Thread-2/INFO]: Running shutdown step 1 finished
[13:54:45] [Thread-2/INFO]: Running shutdown step 2 finished

**Comment by Plagueistry** [comment]
And also a "vlc.log" file which might be useful

-- logger module started --
main debug: VLC media player - 4.0.0-dev Otto Chriek
main debug: Copyright © 1996-2022 the VideoLAN team
main debug: revision 4.0.0-dev-20001-g56a87b96a5
main debug: configured with /builds/videolan/vlc/extras/package/win32/../../../configure  '--enable-update-check' '--enable-lua' '--enable-flac' '--enable-theora' '--enable-avcodec' '--enable-merge-ffmpeg' '--enable-dca' '--enable-libass' '--enable-schroedinger' '--enable-live555' '--enable-shout' '--enable-goom' '--enable-sse' '--enable-libcddb' '--enable-zvbi' '--disable-telx' '--enable-nls' '--host=x86_64-w64-mingw32' '--with-contrib=../contrib/x86_64-w64-mingw32' '--enable-debug' '--enable-qt' '--enable-skins2' '--enable-dvdread' '--enable-caca' 'host_alias=x86_64-w64-mingw32' 'CFLAGS= -D__MSVCRT_VERSION__=0x700 -D_WIN32_WINNT=0x0601 -DWINVER=0x0601 ' 'CPPFLAGS= -D__MSVCRT_VERSION__=0x700 -D_WIN32_WINNT=0x0601 -DWINVER=0x0601' 'CXXFLAGS= -D__MSVCRT_VERSION__=0x700 -D_WIN32_WINNT=0x0601 -DWINVER=0x0601 ' 'PKG_CONFIG=pkg-config' 'PKG_CONFIG_LIBDIR=/usr/x86_64-w64-mingw32/lib/pkgconfig:/usr/lib/x86_64-w64-mingw32/pkgconfig'
main debug: searching plug-in modules
main debug: loading plugins cache file C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test/plugins\plugins.dat
main warning: cannot read C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test/plugins\plugins.dat: No such file or directory
main debug: recursively browsing `C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test/plugins'
main debug: loading plugins cache file C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test\plugins\plugins.dat
main warning: cannot read C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test\plugins\plugins.dat: No such file or directory
main debug: recursively browsing `C:\Users\Senpa\curseforge\minecraft\Instances\Fancy menu test\plugins'
main debug: plug-ins loaded: 67 modules
main debug: looking for logger module matching "any": 4 candidates
file debug: opening logfile `logs/vlc.log'
main debug: using logger module "file"
main debug: looking for tracer module matching "none": 0 candidates
main debug: no tracer modules matched with name none
main debug: translation test: code is "C"
main debug: looking for keystore module matching "memory": 0 candidates
main debug: no keystore modules matched with name memory
main warning: memory keystore init failed
main debug: CPU has capabilities SSE2 SSE3 SSSE3 SSE4.1 FPU 
main debug: exiting
main debug: no exit handler
main debug: removing all interfaces
-- logger module stopped --

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.12.2-1 for Forge 1.19! Thank you both for your help! :)
