### ISSUE TITLE
Can't save custom Mainmenus [1.18.2]

### ISSUE THREAD

**Issue by NXTler** [Keksuccino/FancyMenu#442]
Hey all,
I'm currently in the making of a large modpack and wanted to build a custom Maimenu for it. Though when trying to save the custom Mainmenu I get this error:

> [17:45:14] [Render thread/INFO]: [STDERR]: java.io.IOException: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch
[17:45:14] [Render thread/INFO]: [STDERR]: 	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at java.base/java.io.File.createNewFile(File.java:1043)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.properties.PropertiesSerializer.writeProperties(PropertiesSerializer.java:93)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.helper.CustomizationHelper.saveLayoutTo(CustomizationHelper.java:216)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.helper.CustomizationHelper.saveLayoutTo(CustomizationHelper.java:238)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.helper.layoutcreator.LayoutEditorScreen.lambda$saveLayoutAs$2(LayoutEditorScreen.java:1550)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.gui.screens.popup.TextInputPopup.onEnterPressed(TextInputPopup.java:102)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.input.KeyboardHandler.onKeyPressPost(KeyboardHandler.java:75)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.invokeEvent(EventHandler.java:115)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.callEventsFor(EventHandler.java:102)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.handler$eel000$onKeyboardPressedReleasedPost(class_437.java:7866)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:499)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:380)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:472)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:472)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1147)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
[17:45:14] [Render thread/INFO]: [STDERR]: 	at org.polymc.EntryPoint.main(EntryPoint.java:74)
[17:45:36] [Render thread/INFO]: Stopping!
[17:45:37] [Render thread/INFO]: closing rrp minekea:dynamic_resources

This causes the custom Mainmenu to not get saved and it is not possible to find or load it afterwards.
I'm not sure if this is also true for other menus.
Here is the complete log with mod list:
[latest.log](https://github.com/Keksuccino/FancyMenu/files/9997762/latest.log)

Thanks for any help!

OS: Windows  10, 22H2
FancyMenu: 2.12.7
FabricLoader: 0.14.10
Fabric API: 0.66.0
Minecraft: 1.18.2

**Comment by Keksuccino** [comment]
Update your FancyMenu.
