### ISSUE TITLE
Custom Buttons don't save andvanced sizing / positioning with calculator

### ISSUE THREAD

**Issue by SpigotDE** [Keksuccino/FancyMenu#523]
Video that explains what's going on: https://vimeo.com/804806701

Latest.log: https://gist.github.com/SpigotDE/5001752f343b484136a7ac533c810054

**Comment by SpigotDE** [comment]
Now i got this in my console:

at java.base/java.util.ArrayList.add(ArrayList.java:455)
at java.base/java.util.ArrayList.add(ArrayList.java:467)
at de.keksuccino.konkrete.events.EventHandler.registerEventsFrom(EventHandler.java:29)
at de.keksuccino.konkrete.gui.content.scrollarea.ScrollArea.<init>(ScrollArea.java:50)
at de.keksuccino.fancymenu.menu.fancy.item.items.text.TextCustomizationItem.updateScrollArea(TextCustomizationItem.java:140)
at de.keksuccino.fancymenu.menu.fancy.item.items.text.TextCustomizationItem.lambda$updateContent$0(TextCustomizationItem.java:329)
at java.base/java.lang.Thread.run(Thread.java:833)
[Thread-30/ERROR] Uncaught exception in thread "Thread-30"`

**Comment by SpigotDE** [comment]
I got a fresh latest.log https://gist.github.com/SpigotDE/e98cee3264cea6bfbafb60c3618134a6

On line **738 to 746** 

PS:
Don't mind the chipped:ice tag issue here

**Comment by Keksuccino** [comment]
-- note, please ignore --

- Other report about this issue with video: https://discord.com/channels/704163135787106365/1085569614093758504/1085569614093758504
- Probably caused by the editor saving the placeholders as converted Strings instead of raw ones

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v2.14.0!
