### ISSUE TITLE
Crash when entering the chest, pause menu and so on

### ISSUE THREAD

**Issue by Vingriz** [Keksuccino/FancyMenu#589]
I went to open the pause menu server or chest and after a second it crashes

1. go to the server
2. open pause menu / workbench / chest and so on
3. wait 1-2 seconds
4. Crash games

After 3-4 crash, I realized that if I go to any menu (like a chest, workbench, pause menu, and so on), I crash after 1 or 2 seconds

https://gist.github.com/Vingriz/4b6ca36b69afd225ce266744f3219590

   - OS: Windows 11
   - FancyMenu Version 2.14.9
   - Fabric 0.14.21
   - Minecraft version 1.20
 - Fabric Mods: 
 ```
		advancementplaques: Advancement Plaques 1.4.11
		ambientsounds: AmbientSounds 5.2.20
		betteradvancements: Better Advancements 0.3.2.159
		betterbeds: Better Beds 1.3.0
		betterf3: BetterF3 7.0.1
			cloth-config: Cloth Config v11 11.1.106
				cloth-basic-math: cloth-basic-math 0.6.1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577
		blur: Blur (Fabric) 3.1.0
			midnightlib: MidnightLib 1.4.1
			satin: Satin 1.13.0
		bobby: Bobby 5.0.0
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a82
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b82
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.88
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.88
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.88
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.88
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.88
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.88
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.88
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.88
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.88
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.88
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.88
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.88
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.88
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.88
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.88
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.88
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.88
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.88
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.88
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.88
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.88
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chat_heads: Chat Heads 0.10.18
		clumps: Clumps 11.0.0.2
		collective: Collective 6.57
		continuity: Continuity 3.0.0-beta.2+1.20
		craftpresence: CraftPresence 2.2.1
		creativecore: CreativeCore 2.10.28
			net_minecraftforge_eventbus: eventbus 6.0.3
		dashloader: DashLoader 5.0.0-beta.1+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		dawn: Dawn API 5.0.0
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		dynamiccrosshair: Dynamic Crosshair 7.0.4+1.20
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			yaclx: YetAnotherConfigLibExtensions 1.3+1.20
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		ears: Ears 1.4.6
		elementa: Elementa 590
		emotecraft: Emotecraft 2.2.7-b.build.50
			bendy-lib: Bendy api 4.0.0
			player-animator: Player Animator 1.0.2-rc1+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		equipmentcompare: Equipment Compare 1.3.7
			cardinal-components-base: Cardinal Components API (base) 5.2.0
			cardinal-components-entity: Cardinal Components API (entities) 5.2.0
		essential: Essential 13437+deploy-staging+gd2fc09762
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.0
		extrasounds: ExtraSounds 2.3.1+1.20~lonefelidae16-build.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			soundcategories: Sound Categories 1.2.4+1.20~lonefelidae16-build.1
		fabric-api: Fabric API 0.83.1+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b77
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fallingleaves: Falling Leaves 1.15.2+1.20.1
		fancymenu: FancyMenu 2.14.9
		fastchest: FastChest 1.4+1.20
		ferritecore: FerriteCore 6.0.0
		forgeconfigapiport: Forge Config API Port 7.0.0
		highlighter: Highlighter 1.1.6
		iceberg: Iceberg 1.1.14
		indium: Indium 1.0.18+mc1.20
		inventoryhud: Inventory HUD + 3.4.17
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemborders: Item Borders 1.2.0
		jade: Jade 11.3.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 14.0.0.11
		jeresources: Just Enough Resources 1.4.0.222
		journeymap: Journeymap 5.9.8
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		justenoughprofessions: Just Enough Professions (JEP) 3.0.0
		konkrete: Konkrete 1.6.1
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.4.4
		lithium: Lithium 0.11.2
		loadmyresources: Load My Resources 1.0.4
		minecraft: Minecraft 1.20
		modmenu: Mod Menu 7.0.1
		mousetweaks: Mouse Tweaks 2.25
		mousewheelie: Mouse Wheelie 1.11.1+mc1.20-pre2
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		nether_ores_reborn: Nether Ores Reborn 1.0.0-1.20.1
		notenoughanimations: NotEnoughAnimations 1.6.4
		org_jetbrains_annotations: annotations 13.0
		perspectivemod: Perspective Mod Redux 0.0.5_01
		pickupnotifier: Pick Up Notifier 7.0.0
		plasmovoice: Plasmo Voice 2.0.5
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			javax_inject_javax_inject: javax.inject 1
		prism: Prism 1.0.5
		puzzleslib: Puzzles Lib 7.0.9
		reeses-sodium-options: Reese's Sodium Options 1.6.3+mc1.20.1-build.92
		shulkerboxtooltip: Shulker Box Tooltip 4.0.3+1.20
		smoke_suppression: Smoke Suppression 1.0.16
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.23+mc1.20.1-build.106
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.20-1.1.1
		starlight: Starlight 1.1.2+fabric.dbc156f
		status-effect-bars: Status Effect Bars 1.0.3
		tia: Tiny Item Animations 1.20-1.1
		tlskincape: TLSkinCape 1.32
		treechop: HT's TreeChop 0.18.3
		universal_ores: Universal Ores 1.5.2
		universalcraft: UniversalCraft 277
		viafabric: ViaFabric 0.4.10+39-main
			org_yaml_snakeyaml: snakeyaml 2.0
			viafabric-mc120: ViaFabric for 1.20 0.4.10+39-main
			viaversion: ViaVersion 4.7.0
		vigilance: Vigilance 284
		villagespawnpoint: Village Spawn Point 4.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
		zoomify: Zoomify 2.10.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
```

**Comment by Keksuccino** [comment]
That doesn't sound like it's related to FancyMenu. Sound more like JEI or some of its related mods is causing that.

```
at jeresources.util.LootTableHelper.getLootDataManager(LootTableHelper.java:180) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	at jeresources.util.LootTableHelper.toDrops(LootTableHelper.java:95) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	at jeresources.util.PlantHelper.getSeeds(PlantHelper.java:14) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	at jeresources.entry.PlantEntry.registerGrass(PlantEntry.java:28) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	at jeresources.registry.PlantRegistry.<init>(PlantRegistry.java:25) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	at jeresources.registry.PlantRegistry.getInstance(PlantRegistry.java:19) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:11) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:89) ~[jei-1.20-fabric-14.0.0.11.jar:?]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20-fabric-14.0.0.11.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:89) ~[jei-1.20-fabric-14.0.0.11.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:118) ~[jei-1.20-fabric-14.0.0.11.jar:?]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20-fabric-14.0.0.11.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.20-fabric-14.0.0.11.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:53) ~[jei-1.20-fabric-14.0.0.11.jar:?]
	at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.20-fabric-14.0.0.11.jar:?]
```

**Comment by Vingriz** [comment]
I removed these mods and it still crashes when I go into the chest

**Comment by Vingriz** [comment]
i think it's not fancymenu

**Comment by Vingriz** [comment]
LegendaryTooltips-1.20.1-fabric-1.4.4.jar crash my game :P

**Comment by Vingriz** [comment]
but i have 1 more problem
Animation background dont work (all background animations change to dirt background)
static backround is work

**Comment by Vingriz** [comment]
I fixed all the problems but LegendaryTooltips crush my game when i open the menu/chest and so on
