### ISSUE TITLE
[Crash] Custom Singleplayer Button - Rendering Screen - NullPointerException

### ISSUE THREAD

**Issue by xR4YM0ND** [Keksuccino/FancyMenu#637]
The Modpack crashes everytime i click on the custom singleplayer button...

Fabric 1.20.1 - 0.15.3
[latest.log](https://gist.github.com/xR4YM0ND/f62a61dd1767a5b2446bb93f439d561d)

[Configs](https://github.com/xR4YM0ND/Aged/tree/2.2.0/overrides/config/fancymenu)

[Aged Modpack v 2.2.0](https://modrinth.com/modpack/aged/version/2.2.0)

```js
[10:11:26] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:954) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.NullPointerException: Screen cannot be null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.afterRender(ScreenEvents.java:135) ~[fabric-screen-api-v1-2.0.7+b3afc78b77-1b94cdbf480387db.jar:?]
	at net.minecraft.class_757.handler$efk000$fabric-screen-api-v1$onAfterRenderScreen(class_757.java:7144) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	... 6 more
```

I tried the action for the custom button:

opengui - net.minecraft.class_526

then i also tried:

mimicbutton (singleplayer button) - net.minecraft.class_442:button_compatibility_id:mc_titlescreen_singleplayer_button

with both ways the modpack crashes...

Any way to fix this myself?

**Comment by Kevinello** [comment]
i can reproduce this crash too.
remove fancymenu and create world works well

log file attached
[crash-2024-01-18_19.37.11-client.txt](https://github.com/Keksuccino/FancyMenu/files/13976073/crash-2024-01-18_19.37.11-client.txt)

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
