### ISSUE TITLE
[1.18.2] Incompatibility with Debugify

### ISSUE THREAD

**Issue by Stupidplays** [Keksuccino/FancyMenu#700]
**Describe the issue**
When I enable these mod, the game had crash and it is not even load the loading screen. (The entire debug log doesn't even explained what mod cause this issue.) 

**Game Log**
[debug.log](https://github.com/Keksuccino/FancyMenu/files/14312789/debug.log)
[latest.log](https://github.com/Keksuccino/FancyMenu/files/14312798/latest.log)

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/110560508/1d5dbe19-5c21-4628-8e9c-509305c6c91f)

Translation:
An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit Code: 1

**Basic Informations (please complete the following information):**
 - Windows 10
 - FancyMenu 3.0.6
 - Forge 40.2.17
 - Minecraft 1.18.2
 - Active Mods: 
      Cloth Config API (Fabric/Forge/NeoForge)
      Debugify
      FancyMenu
      Konkrete [Forge]
      Melody

**Comment by Keksuccino** [comment]
You can fix this by using [Modern Debugify](https://www.curseforge.com/minecraft/mc-mods/modern-debugify) instead.
Debugify for 1.18.2 is hella outdated and somehow kills JarInJar'd MixinExtras.


Actual crash reason with normal Debugify:
```
Exception in thread "main" java.lang.module.ResolutionException: Modules debugify and MixinExtras export package com.llamalad7.mixinextras to module fancymenu
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
04:48:15.185
Process crashed with exit code 1
```
