### ISSUE TITLE
`StackOverflowError` with some mod

### ISSUE THREAD

**Issue by SettingDust** [Keksuccino/FancyMenu#728]
**Describe the bug**
```
java.lang.StackOverflowError: null
	at com.google.gson.internal.$Gson$Types.getGenericSupertype($Gson$Types.java:246) ~[gson-2.10.jar:?]
	at com.google.gson.internal.$Gson$Types.getSupertype($Gson$Types.java:291) ~[gson-2.10.jar:?]
	at com.google.gson.internal.$Gson$Types.getCollectionElementType($Gson$Types.java:309) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:295) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:295) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:295) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1213) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1062) ~[gson-2.10.jar:?]
	at com.github.einjerjar.mc.keymap.keys.layout.KeyLayout.tryLoadLayout(KeyLayout.java:139) ~[keymap-0.9.0-beta.1+1.20.1-fabric.jar:?]
	at com.github.einjerjar.mc.keymap.keys.layout.KeyLayout.loadKeys(KeyLayout.java:126) ~[keymap-0.9.0-beta.1+1.20.1-fabric.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.handler$kid005$keymap$onInit(TitleScreen.java:5025) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen.java) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.clearAndInit(Screen.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.initTabNavigation(Screen.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.resize(Screen.java:404) ~[client-intermediary.jar:?]
	at de.keksuccino.fancymenu.customization.ScreenCustomization.reInitCurrentScreen(ScreenCustomization.java:289) ~[fancymenu_fabric_3.1.2_MC_1.20.1.jar:?]
	at net.minecraft.client.gui.screen.Screen.handler$ilo000$fancymenu$afterInitFancyMenu(Screen.java:10699) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:305) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.clearAndInit(Screen.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.initTabNavigation(Screen.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.resize(Screen.java:404) ~[client-intermediary.jar:?]
	at de.keksuccino.fancymenu.customization.ScreenCustomization.reInitCurrentScreen(ScreenCustomization.java:289) ~[fancymenu_fabric_3.1.2_MC_1.20.1.jar:?]
	at net.minecraft.client.gui.screen.Screen.handler$ilo000$fancymenu$afterInitFancyMenu(Screen.java:10699) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:305) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.clearAndInit(Screen.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.initTabNavigation(Screen.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.resize(Screen.java:404) ~[client-intermediary.jar:?]
	at de.keksuccino.fancymenu.customization.ScreenCustomization.reInitCurrentScreen(ScreenCustomization.java:289) ~[fancymenu_fabric_3.1.2_MC_1.20.1.jar:?]
	at net.minecraft.client.gui.screen.Screen.handler$ilo000$fancymenu$afterInitFancyMenu(Screen.java:10699) ~[client-intermediary.jar:?]
```

**To Reproduce**
I need the owner to point out the possible reason for finding the mod.
keymap and FancyMenu are working in new install

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
https://pastes.dev/5QdeKhYXWD

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] Windows
 - FancyMenu Version [e.g. 0.2] 3.1.2
 - Forge/Fabric Version [e.g. 31.2.24] 0.15.7
 - Minecraft Version [e.g. 1.15.1] 1.20.1
 - Active Mods [e.g. Optifine, 5zig, TooManyItems] So much. It's in log

**Comment by SettingDust** [comment]
same as https://github.com/Keksuccino/FancyMenu/issues/747
