### ISSUE TITLE
Incompatibility with "Modern Online Picture Frames"

### ISSUE THREAD

**Issue by Qian-F** [Keksuccino/FancyMenu#776]
**Describe the issue**
Crash on startup

**Game Log**
```
Exception in thread "main" java.lang.module.ResolutionException: Modules opf and com.madgag.gif.fmsware export package com.madgag.gif.fmsware to module bakery
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: windows
 - FancyMenu Version 3.1.4
 - Forge Version 43.3.9
 - Minecraft Version 1.19.2

**Comment by Qian-F** [comment]
https://www.curseforge.com/minecraft/mc-mods/online-picture-frame

**Comment by Keksuccino** [comment]
Please send an actual log, thank you. Latest.log or crash log.

**Comment by Keksuccino** [comment]
Nvm, that's not something I can fix on my end. The other mod needs to fix that if I'm not wrong.

**Comment by Qian-F** [comment]
I noticed that it happened when updating from version 3.1.2 to 3.1.4.

**Comment by Keksuccino** [comment]
Yes, because I switched to a new library to decode GIF images. Looks like the other mod uses the same mod, but doesn't correctly Jar-in-Jar's it and instead just ships it as part of the main JAR, which leads to compatibility issues. I'm pretty sure that's the other mod's fault. All I do is correctly Jar-in-Jar the [library](https://github.com/rtyley/animated-gif-lib-for-java).

**Comment by Keksuccino** [comment]
Upadate: I opened [an issue](https://legacy.curseforge.com/minecraft/mc-mods/online-picture-frame/issues/8) in OPF's issue tracker.

**Comment by Keksuccino** [comment]
Please don't close open issues, thank you.

**Comment by Qian-F** [comment]
I have found better alternatives that achieve the same functionality.
LittlePictureFrames: https://www.curseforge.com/minecraft/mc-mods/littleframes

**Comment by Keksuccino** [comment]
Will close this since a good alternative is available! :) Thank you for posting the mod link to the alternative! :)
