### ISSUE TITLE
Game crashes when trying to edit the pause menu ( / by zero )

### ISSUE THREAD

**Issue by vizthex123** [Keksuccino/FancyMenu#781]
**Describe the bug**
As the title says, the game crashes when trying to edit the pause menu. I just wanted to restore the normal layout...

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Enter a world
2. Open the pause menu
3. Try to edit its layout

**Expected behavior**
Either the mod saying "no, you can't edit this UI" or letting me edit said UI.

**Game Log**
[Log](https://gist.github.com/vizthex123/e189922d0880df9eb0f6cfde54cde16f)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: 3.1.5
 - Forge/Fabric Version: 47.2.23. Downgrading does not fix the crash.
 - Minecraft Version: 1.20.1
 - Active Mods: 180. I can add a screenshot of the list or something if needed.

**Comment by Keksuccino** [comment]
Unable to reproduce in FancyMenu v3.2.2. If it still happens for you in this version, please send me your `config/fancymenu` folder.

**Comment by Brittank88** [comment]
Requesting this be reopened as it is occurring in `v3.2.3`.

Crash Report:
[crash-2024-07-24_13.17.49-client.txt](https://github.com/user-attachments/files/16356674/crash-2024-07-24_13.17.49-client.txt)

`config/fancymenu`:
[fancymenu.zip](https://github.com/user-attachments/files/16356676/fancymenu.zip)

**Comment by Brittank88** [comment]
Bump just to ask if there's any more info I could be providing?

I'd love to fix up the pause menu as there are overlapping buttons, but I'm powerless here. Understand though if it's tough to tackle right now. 😄 

Is there any way I could manually work around this?

**Comment by Keksuccino** [comment]
```
java.lang.ArithmeticException: / by zero
	at java.lang.Math.floorDiv(Math.java:1225) ~[?:?] {re:mixin}
	at net.minecraft.util.Mth.m_184652_(Mth.java:730) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:math.sine_lut.MixinMathHelper,pl:mixin:A}
	at net.minecraft.client.gui.GuiGraphics.m_280358_(GuiGraphics.java:441) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.blitRepeating(GuiGraphics.java:431) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280543_(GuiGraphics.java:418) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280195_(GuiGraphics.java:406) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280027_(GuiGraphics.java:386) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.AbstractButton.m_87963_(AbstractButton.java:33) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fancymenu.mixins.json:client.MixinAbstractButton,pl:mixin:APP:tacz.mixins.json:client.AbstractButtonMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.AbstractWidget.m_88315_(AbstractWidget.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fancymenu.mixins.json:client.IMixinAbstractWidget,pl:mixin:APP:fancymenu.mixins.json:client.MixinAbstractWidget,pl:mixin:APP:yungsmenutweaks.mixins.json:AbstractWidgetMixin,pl:mixin:APP:physicsmod.mixins.json:guiphysics.MixinAbstractWidget,pl:mixin:APP:physicsmod.mixins.json:guiphysics.MixinAbstractWidgetAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at de.keksuccino.fancymenu.customization.element.elements.button.custombutton.ButtonElement.renderElementWidget(ButtonElement.java:107) ~[fancymenu_forge_3.2.3_MC_1.20.1.jar%23502!/:3.2.3] {re:classloading}
	at de.keksuccino.fancymenu.customization.element.elements.button.vanillawidget.VanillaWidgetElement.renderElementWidget(VanillaWidgetElement.java:65) ~[fancymenu_forge_3.2.3_MC_1.20.1.jar%23502!/:3.2.3] {re:classloading}
	at de.keksuccino.fancymenu.customization.element.elements.button.custombutton.ButtonElement.m_88315_(ButtonElement.java:99) ~[fancymenu_forge_3.2.3_MC_1.20.1.jar%23502!/:3.2.3] {re:classloading}
	at de.keksuccino.fancymenu.customization.element.editor.AbstractEditorElement.m_88315_(AbstractEditorElement.java:508) ~[fancymenu_forge_3.2.3_MC_1.20.1.jar%23502!/:3.2.3] {re:classloading}
	at de.keksuccino.fancymenu.customization.layout.editor.LayoutEditorScreen.renderElements(LayoutEditorScreen.java:293) ~[fancymenu_forge_3.2.3_MC_1.20.1.jar%23502!/:3.2.3] {re:classloading}
	at de.keksuccino.fancymenu.customization.layout.editor.LayoutEditorScreen.m_88315_(LayoutEditorScreen.java:246) ~[fancymenu_forge_3.2.3_MC_1.20.1.jar%23502!/:3.2.3] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:seamless_loading_screen-common.mixins.json:ScreenMixin,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:configured.common.mixins.json:client.ScreenMixin,pl:mixin:APP:fancymenu.mixins.json:client.IMixinScreen,pl:mixin:APP:fancymenu.mixins.json:client.MixinScreen,pl:mixin:APP:nerb-common.mixins.json:ScreenMixin,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:APP:reblured.mixins.json:ScreenMixin,pl:mixin:APP:yungsmenutweaks.mixins.json:ScreenMixin,pl:mixin:APP:konkrete.mixin.json:IMixinScreen,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinScreen,pl:mixin:APP:physicsmod.mixins.json:guiphysics.MixinScreen,pl:mixin:APP:tenshilib.mixins.json:ScreenAccessor,pl:mixin:APP:panorama_screen-common.mixins.json:ScreenMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:ScreenMixin,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:424) ~[forge-1.20.1-47.1.106-universal.jar%23641!/:?] {re:mixin,re:classloading,pl:mixin:APP:myserveriscompatible.mixins.json:MixinClientHooks,pl:mixin:APP:sodium-extra.mixins.json:fog.ForgeHooksClientMixin,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:417) ~[forge-1.20.1-47.1.106-universal.jar%23641!/:?] {re:mixin,re:classloading,pl:mixin:APP:myserveriscompatible.mixins.json:MixinClientHooks,pl:mixin:APP:sodium-extra.mixins.json:fog.ForgeHooksClientMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$drawScreen$281(GameRenderer.java) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin,pl:mixin:APP:railways-common.mixins.json:client.MixinGameRenderer,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin,pl:mixin:APP:pointblank.mixins.json:GameRendererMixin,pl:mixin:APP:pointblank.mixins.json:GameRendererAccessorMixin,pl:mixin:APP:create_train_perspective.mixins.json:GameRendererMixin,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:physicsmod.mixins.json:MixinGameRenderer,pl:mixin:APP:physicsmod.mixins.json:ocean.MixinVSGameRenderer,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin,pl:mixin:APP:seamless_loading_screen-common.mixins.json:GameRendererMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer,pl:mixin:APP:enhancedvisuals.mixins.json:GameRendererMixin,pl:mixin:APP:darkness.client.json:MixinGameRenderer,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:tacz.mixins.json:client.GameRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:shouldersurfing.common.mixins.json:GameRendererAccessor,pl:mixin:APP:shouldersurfing.common.mixins.json:MixinGameRenderer,pl:mixin:APP:corgilib.mixins.json:client.GameRendererMixin,pl:mixin:APP:panorama_screen-common.mixins.json:GameRendererMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat1204minus.compat1193plus.GameRendererMixin,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.wrapOperation$baf000$wrapRenderScreenFancyMenu(GameRenderer.java:3599) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin,pl:mixin:APP:railways-common.mixins.json:client.MixinGameRenderer,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin,pl:mixin:APP:pointblank.mixins.json:GameRendererMixin,pl:mixin:APP:pointblank.mixins.json:GameRendererAccessorMixin,pl:mixin:APP:create_train_perspective.mixins.json:GameRendererMixin,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:physicsmod.mixins.json:MixinGameRenderer,pl:mixin:APP:physicsmod.mixins.json:ocean.MixinVSGameRenderer,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin,pl:mixin:APP:seamless_loading_screen-common.mixins.json:GameRendererMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer,pl:mixin:APP:enhancedvisuals.mixins.json:GameRendererMixin,pl:mixin:APP:darkness.client.json:MixinGameRenderer,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:tacz.mixins.json:client.GameRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:shouldersurfing.common.mixins.json:GameRendererAccessor,pl:mixin:APP:shouldersurfing.common.mixins.json:MixinGameRenderer,pl:mixin:APP:corgilib.mixins.json:client.GameRendererMixin,pl:mixin:APP:panorama_screen-common.mixins.json:GameRendererMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat1204minus.compat1193plus.GameRendererMixin,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:969) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin,pl:mixin:APP:railways-common.mixins.json:client.MixinGameRenderer,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin,pl:mixin:APP:pointblank.mixins.json:GameRendererMixin,pl:mixin:APP:pointblank.mixins.json:GameRendererAccessorMixin,pl:mixin:APP:create_train_perspective.mixins.json:GameRendererMixin,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:physicsmod.mixins.json:MixinGameRenderer,pl:mixin:APP:physicsmod.mixins.json:ocean.MixinVSGameRenderer,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin,pl:mixin:APP:seamless_loading_screen-common.mixins.json:GameRendererMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer,pl:mixin:APP:enhancedvisuals.mixins.json:GameRendererMixin,pl:mixin:APP:darkness.client.json:MixinGameRenderer,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:tacz.mixins.json:client.GameRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:shouldersurfing.common.mixins.json:GameRendererAccessor,pl:mixin:APP:shouldersurfing.common.mixins.json:MixinGameRenderer,pl:mixin:APP:corgilib.mixins.json:client.GameRendererMixin,pl:mixin:APP:panorama_screen-common.mixins.json:GameRendererMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat1204minus.compat1193plus.GameRendererMixin,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23636!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:APP:physicsmod.mixins.json:MixinMain,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.2.2.jar:47.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
```

**Comment by Keksuccino** [comment]
Well I just realized I fixed this already (probably fixed in FMv3.3.0) lmao
Will close this now. It shouldn't crash anymore.
