### ISSUE TITLE
Crashed with my large modpack

### ISSUE THREAD

**Issue by Thunderrock424242** [Keksuccino/FancyMenu#789]
**Describe the issue**
What exactly is telling you that the mod is incompatible? all I know is when I added the mod to my modpack it started crashing if I removed it it would work as normal.

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https/gist.github.com and send the link.
[link is here](https://gist.github.com/Thunderrock424242/ad62299ffdf966fc2ddfb832a3d259e2) lmk if you need more logs
**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 3.1.5
 - Forge/Fabric Version forge 47.2.0
 - Minecraft Version [e.g. 1.15.1]
 - Active Mods mod list is way to big so if you want to see the list its in the latest.log

**Comment by Keksuccino** [comment]
I don't see why this should be related to FancyMenu. It crashes because the local player is accessed too early.
Did you open a specific screen or something right before it crashed?

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.player.LocalPlayer.m_6117_()" because "this.f_91074_" is null
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1957) ~[client-1.20.1-20230612.114412-srg.jar%231066!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%231066!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%231066!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231066!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

**Comment by Keksuccino** [comment]
Please also check the [incompatibility list](https://docs.fancymenu.net/en/incompatibility-list).

**Comment by Thunderrock424242** [comment]
> Please also check the [incompatibility list](https://docs.fancymenu.net/en/incompatibility-list).

remove loading screen caused it
